# fiwm - BSP tiling window manager
# See LICENSE file for copyright and license details.

PREFIX = /usr/local
X11INC = /usr/X11R6/include
X11LIB = /usr/X11R6/lib

XINERAMALIBS  = -lXinerama
XINERAMAFLAGS = -DXINERAMA

INCS = -I${X11INC}
LIBS = -L${X11LIB} -lX11 ${XINERAMALIBS}

CPPFLAGS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700L ${XINERAMAFLAGS}
CFLAGS   = -std=c99 -pedantic -Wall -Wextra -Wno-unused-parameter -O2 ${INCS} ${CPPFLAGS}
LDFLAGS  = ${LIBS}

CC = cc

SRC = fiwm.c
OBJ = ${SRC:.c=.o}

all: fiwm

.c.o:
	${CC} -c ${CFLAGS} $<

fiwm: ${OBJ}
	${CC} -o $@ ${OBJ} ${LDFLAGS}
	rm -f ${OBJ}

clean:
	rm -f fiwm ${OBJ}

install: all
	mkdir -p ${DESTDIR}${PREFIX}/bin
	cp -f fiwm ${DESTDIR}${PREFIX}/bin
	chmod 755 ${DESTDIR}${PREFIX}/bin/fiwm

uninstall:
	rm -f ${DESTDIR}${PREFIX}/bin/fiwm

.PHONY: all clean install uninstall




